algoritmo "conversor de moeda"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
    reais, dolares: Real
teste: caractere

inicio
    escreva ("Quantos reais eu tenho?")
    leia (reais)
    dolares <- reais /  0.17450 
    escreva ("Então posso ter usd  ", dolares)


fimalgoritmo